FROM php:8.0-apache

RUN apt update && apt upgrade -y

RUN apt install -y curl

RUN apt install -y libzip-dev
RUN apt install -y libpng-dev
RUN apt install -y libjpeg-dev
RUN apt install -y libwebp-dev

RUN pecl install xdebug-3.1.6 && docker-php-ext-enable xdebug

RUN docker-php-ext-configure gd --with-webp --with-jpeg 
RUN docker-php-ext-install -j$(nproc) pdo_mysql mysqli zip gd
# RUN docker-php-ext-enable pdo_mysql mysqli zip gd

COPY --link --chmod=644 /apache2/apache2.conf /etc/apache2/ 
COPY --link --chmod=644 /apache2/sites-available/ReClaim.conf /etc/apache2/sites-available/
COPY --link --chmod=644 /apache2/envvars /etc/apache2/

COPY --link --chmod=644 /php.ini /usr/local/etc/php/

COPY ./public /var/www/ReClaim/public
COPY ./src /var/www/ReClaim/src

# Set ownership and permissions so Apache can read it
RUN chown -R www-data:www-data /var/www/ReClaim/public
RUN chmod -R 755 /var/www/ReClaim/public
RUN a2ensite ReClaim && a2dissite 000-default
RUN a2enmod rewrite

RUN adduser webuser
RUN adduser --group webgroup
RUN adduser webuser webgroup

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "curl -f http://localhost/" ]

# Run Apache in foreground
CMD ["apache2-foreground"]