name: Deploy Re:Claim to Production

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Build Frontend
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install --omit=dev
            fi
            npm run build --if-present
          fi
      

      - name: Build Backend
        run: |
          if [ -f composer.json ]; then
            composer install --no-dev --optimize-autoloader
          fi
          
      - name: Deploy Frontend
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_RECLAIM_PRODUCTION }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: "/home/${{ secrets.SSH_USERNAME }}/public_html/reclaim"
          SOURCE: "./public/"
          EXCLUDE: "/.git/, /.github/, /node_modules/"

      - name: Deploy Backend
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_RECLAIM_PRODUCTION }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: "/home/${{ secrets.SSH_USERNAME }}/public_html/reclaim"
          SOURCE: "./src"
          EXCLUDE: "/.git/, /.github/, /node_modules/"
